name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print build information
        run: "echo head_ref: ${{ github.head_ref }}, ref: ${{ github.ref }}"
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set up staticcheck and workflowcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest github.com/kisielk/errcheck@latest go.temporal.io/sdk/contrib/tools/workflowcheck@latest

      - name: Staticcheck hello-workflow
        run: staticheck .
        working-directory: exercises/hello-workflow/solution/worker

      - name: Staticcheck farewell-workflow
        run: staticheck .
        working-directory: exercises/farewell-workflow/solution/worker

      - name: Workflowcheck hello-workflow
        run: workflowcheck -show-pos .
        working-directory: exercises/hello-workflow/solution/worker

      - name: Workflowcheck farewell-workflow
        run: workflowcheck -show-pos .
        working-directory: exercises/farewell-workflow/solution/worker

      - name: Build hello-workflow
        run: go build
        working-directory: exercises/hello-workflow/solution/worker

      - name: Build farewell-workflow
        run: go build
        working-directory: exercises/farewell-workflow/solution/worker